environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install -g typings
  - typings install
  - npm install

test_script:
  - npm run build
  - npm test

build: off
